#!/usr/bin/env node
"use strict";
/*
 * Controlled workflow for the project_implementation evidence fingerprint —
 * replaces hand-editing 240 hash occurrences as a "normal" workflow step.
 *
 * Modes:
 *   check   — compute the actual fingerprint, compare to stored, change
 *             nothing. No workbook needed (this is a pure yaml+js+
 *             sources.json operation).
 *   review  — write a machine-readable, timestamped drift report to
 *             protocol/generated/.fingerprint-review.json. Changes nothing
 *             else. Captures enough about the CURRENT exact source state
 *             (content digests + the exact byte count of the old
 *             fingerprint string in each citation file) that `accept` can
 *             later prove the source hasn't moved since this review.
 *   accept  — re-verifies every one of review's captured conditions against
 *             the CURRENT source state, runs the canonical validator, and
 *             ONLY THEN rewrites the fingerprint citations in
 *             protocol/registers.canonical.json and
 *             protocol/evidence/sources.json — atomically, with a post-
 *             write self-check, and a rollback on any inconsistency.
 *
 * This does NOT touch protocol/generated/claim_matrix.json (regenerated by
 * tools/protocol/pipeline.js build from the files this tool DOES change —
 * that's the pipeline's job, not this tool's) and does not require the
 * private evidence workbook for check/review/accept (only pipeline.js
 * build/check ever needs the workbook).
 *
 * Exit codes: 0 success, 1 a check/reason-coded refusal, 2 usage error.
 * Every refusal prints a stable `reasonCode` (see REASON below and
 * tools/protocol/lib/fingerprint.js's REASON) — never a raw stack trace,
 * and never treats "no error text seen" as success.
 */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { spawnSync } = require("child_process");
const fp = require("./lib/fingerprint");

const ROOT = path.join(__dirname, "..", "..");
const REVIEW_PATH = path.join(ROOT, "protocol", "generated", ".fingerprint-review.json");
const CITATION_FILES = [fp.SOURCES_JSON_RELATIVE_PATH, path.join("protocol", "registers.canonical.json")];
const DEFAULT_REVIEW_TTL_SECONDS = 24 * 60 * 60; // 24h — a review is a short-lived workflow artifact, not a standing approval

const REASON = Object.freeze({
  ...fp.REASON,
  REVIEW_MISSING: "REVIEW_MISSING",
  REVIEW_MALFORMED: "REVIEW_MALFORMED",
  REVIEW_STALE: "REVIEW_STALE",
  REVIEW_SOURCE_CHANGED: "REVIEW_SOURCE_CHANGED",
  REVIEW_SOURCES_JSON_CHANGED: "REVIEW_SOURCES_JSON_CHANGED",
  REVIEW_CANONICAL_CHANGED: "REVIEW_CANONICAL_CHANGED",
  CANONICAL_VALIDATION_FAILED: "CANONICAL_VALIDATION_FAILED",
  REPLACEMENT_COUNT_MISMATCH: "REPLACEMENT_COUNT_MISMATCH",
  ACCEPT_VERIFICATION_FAILED: "ACCEPT_VERIFICATION_FAILED",
  REVIEW_OK: "REVIEW_OK",
  ACCEPT_OK: "ACCEPT_OK",
  NOTHING_TO_ACCEPT: "NOTHING_TO_ACCEPT",
});

function fail(reasonCode, detail) {
  const payload = { ok: false, reasonCode, detail: detail || null };
  process.stdout.write(`${JSON.stringify(payload)}\n`);
  console.error(`${reasonCode}${detail ? `: ${detail}` : ""}`);
  process.exit(1);
}

function usageError(message) {
  console.error(`USAGE: node tools/protocol/fingerprint.js check|review|accept [--root <path>] [--review-path <path>] [--ttl-seconds <n>]`);
  if (message) console.error(message);
  process.exit(2);
}

function sha256File(p) {
  return crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex");
}

function countOccurrences(haystack, needle) {
  if (!needle) return 0;
  let count = 0;
  let idx = 0;
  for (;;) {
    idx = haystack.indexOf(needle, idx);
    if (idx === -1) break;
    count += 1;
    idx += needle.length;
  }
  return count;
}

function runValidator(root) {
  const result = spawnSync(process.execPath, [path.join(root, "test", "register_catalog", "validate.js")], {
    cwd: root,
    encoding: "utf8",
  });
  return { ok: result.status === 0, output: `${result.stdout || ""}${result.stderr || ""}` };
}

// --- mode: check -------------------------------------------------------
function modeCheck(root) {
  const result = fp.checkFingerprint(root);
  process.stdout.write(`${JSON.stringify(result)}\n`);
  if (!result.ok) {
    console.error(`${result.reasonCode}${result.detail ? `: ${result.detail}` : ""}`);
    process.exit(1);
  }
  console.log(`FINGERPRINT_MATCH actual=${result.actual}`);
  process.exit(0);
}

// --- mode: review --------------------------------------------------------
function modeReview(root, reviewPath, ttlSeconds) {
  let actual;
  try {
    actual = fp.computeImplementationFingerprint(root);
  } catch (err) {
    return fail(err.reasonCode || "UNKNOWN_ERROR", err.message);
  }
  let storedInfo;
  try {
    storedInfo = fp.readStoredFingerprint(root);
  } catch (err) {
    return fail(err.reasonCode || "UNKNOWN_ERROR", err.message);
  }
  const stored = storedInfo.storedFingerprint;

  const canonicalPath = path.join(root, "protocol", "registers.canonical.json");
  const nonRegisterPath = path.join(root, "protocol", "non_register_entities.canonical.json");
  if (!fs.existsSync(canonicalPath)) return fail(REASON.SOURCE_FILE_MISSING, "protocol/registers.canonical.json");
  if (!fs.existsSync(nonRegisterPath)) return fail(REASON.SOURCE_FILE_MISSING, "protocol/non_register_entities.canonical.json");

  const citationCounts = {};
  for (const relPath of CITATION_FILES) {
    const text = fs.readFileSync(path.join(root, relPath), "utf8");
    citationCounts[relPath] = countOccurrences(text, stored);
  }
  const expectedReplacementCount = Object.values(citationCounts).reduce((a, b) => a + b, 0);

  const now = Date.now();
  const review = {
    schema_version: 1,
    reviewed_at_iso: new Date(now).toISOString(),
    expires_at_iso: new Date(now + ttlSeconds * 1000).toISOString(),
    ttl_seconds: ttlSeconds,
    actual_fingerprint: actual,
    stored_fingerprint: stored,
    drift_present: actual !== stored,
    // Digests captured NOW so `accept` can prove nothing moved since this
    // review — every one is re-verified fresh at accept time, never trusted.
    source_state_digest: fp.sha256(Buffer.from(actual)), // yaml+js content is exactly what `actual` already hashes
    sources_json_digest_excluding_fingerprint: (() => {
      const doc = JSON.parse(JSON.stringify(storedInfo.doc));
      const impl = doc.sources.find((s) => s.source_id === fp.IMPLEMENTATION_SOURCE_ID);
      impl.fingerprint = "<MASKED>";
      return fp.sha256(Buffer.from(JSON.stringify(doc)));
    })(),
    canonical_digest: sha256File(canonicalPath),
    non_register_canonical_digest: sha256File(nonRegisterPath),
    citation_counts: citationCounts,
    expected_replacement_count: expectedReplacementCount,
  };

  fs.mkdirSync(path.dirname(reviewPath), { recursive: true });
  const staged = `${reviewPath}.tmp-${process.pid}`;
  fs.writeFileSync(staged, `${JSON.stringify(review, null, 2)}\n`);
  fs.renameSync(staged, reviewPath);

  process.stdout.write(`${JSON.stringify({ ok: true, reasonCode: REASON.REVIEW_OK, review })}\n`);
  console.log(`REVIEW_OK drift_present=${review.drift_present} expected_replacement_count=${expectedReplacementCount} -> ${reviewPath}`);
  process.exit(0);
}

// --- mode: accept ----------------------------------------------------------
function modeAccept(root, reviewPath) {
  if (!fs.existsSync(reviewPath)) return fail(REASON.REVIEW_MISSING, reviewPath);
  let review;
  try {
    review = JSON.parse(fs.readFileSync(reviewPath, "utf8"));
  } catch (err) {
    return fail(REASON.REVIEW_MALFORMED, err.message);
  }
  if (!review || typeof review !== "object" || typeof review.stored_fingerprint !== "string") {
    return fail(REASON.REVIEW_MALFORMED, "missing required fields");
  }

  if (Date.now() > Date.parse(review.expires_at_iso)) {
    return fail(REASON.REVIEW_STALE, `review expired at ${review.expires_at_iso}`);
  }

  let actualNow;
  try {
    actualNow = fp.computeImplementationFingerprint(root);
  } catch (err) {
    return fail(err.reasonCode || "UNKNOWN_ERROR", err.message);
  }
  if (actualNow !== review.actual_fingerprint) {
    return fail(REASON.REVIEW_SOURCE_CHANGED, `batterylifepo4.yaml/jk_bms.js changed since review (review saw ${review.actual_fingerprint}, now ${actualNow})`);
  }

  let storedInfo;
  try {
    storedInfo = fp.readStoredFingerprint(root);
  } catch (err) {
    return fail(err.reasonCode || "UNKNOWN_ERROR", err.message);
  }
  const sourcesDigestNow = (() => {
    const doc = JSON.parse(JSON.stringify(storedInfo.doc));
    const impl = doc.sources.find((s) => s.source_id === fp.IMPLEMENTATION_SOURCE_ID);
    impl.fingerprint = "<MASKED>";
    return fp.sha256(Buffer.from(JSON.stringify(doc)));
  })();
  if (sourcesDigestNow !== review.sources_json_digest_excluding_fingerprint) {
    return fail(REASON.REVIEW_SOURCES_JSON_CHANGED, "protocol/evidence/sources.json changed (outside the fingerprint field) since review");
  }
  if (storedInfo.storedFingerprint !== review.stored_fingerprint) {
    return fail(REASON.REVIEW_SOURCES_JSON_CHANGED, `stored fingerprint changed since review (review saw ${review.stored_fingerprint}, now ${storedInfo.storedFingerprint})`);
  }

  const canonicalPath = path.join(root, "protocol", "registers.canonical.json");
  const nonRegisterPath = path.join(root, "protocol", "non_register_entities.canonical.json");
  if (!fs.existsSync(canonicalPath)) return fail(REASON.SOURCE_FILE_MISSING, "protocol/registers.canonical.json");
  if (!fs.existsSync(nonRegisterPath)) return fail(REASON.SOURCE_FILE_MISSING, "protocol/non_register_entities.canonical.json");
  if (sha256File(canonicalPath) !== review.canonical_digest) {
    return fail(REASON.REVIEW_CANONICAL_CHANGED, "protocol/registers.canonical.json changed since review");
  }
  if (sha256File(nonRegisterPath) !== review.non_register_canonical_digest) {
    return fail(REASON.REVIEW_CANONICAL_CHANGED, "protocol/non_register_entities.canonical.json changed since review");
  }

  if (actualNow === storedInfo.storedFingerprint) {
    // No drift: nothing to replace. Idempotent success, not an error.
    process.stdout.write(`${JSON.stringify({ ok: true, reasonCode: REASON.NOTHING_TO_ACCEPT, fingerprint: actualNow })}\n`);
    console.log(`NOTHING_TO_ACCEPT fingerprint already current: ${actualNow}`);
    process.exit(0);
  }

  const validation = runValidator(root);
  if (!validation.ok) {
    return fail(REASON.CANONICAL_VALIDATION_FAILED, validation.output.trim().split("\n").slice(-5).join(" | "));
  }

  // Re-scan the exact same files, right now, for the OLD fingerprint —
  // must match what review recorded, or the on-disk state has moved in a
  // way none of the digest checks above happen to cover (e.g. a citation
  // file edited in a way that preserves its overall content digest is not
  // possible with sha256, so this is a second, independent, direct proof
  // rather than a defense against a specific attack).
  const oldValue = review.stored_fingerprint;
  const backups = new Map();
  const actualCounts = {};
  for (const relPath of CITATION_FILES) {
    const full = path.join(root, relPath);
    const text = fs.readFileSync(full, "utf8");
    actualCounts[relPath] = countOccurrences(text, oldValue);
    backups.set(full, text);
  }
  const actualTotal = Object.values(actualCounts).reduce((a, b) => a + b, 0);
  if (actualTotal !== review.expected_replacement_count) {
    return fail(
      REASON.REPLACEMENT_COUNT_MISMATCH,
      `expected=${review.expected_replacement_count} actual=${actualTotal} (${JSON.stringify(actualCounts)})`
    );
  }

  // Atomic-ish replace: write all staged files first, then rename all —
  // if any staging write fails, nothing on the real path has moved yet.
  const staged = [];
  try {
    for (const [full, text] of backups) {
      const replaced = text.split(oldValue).join(actualNow);
      const stagedPath = `${full}.tmp-${process.pid}`;
      fs.writeFileSync(stagedPath, replaced);
      staged.push([stagedPath, full]);
    }
    for (const [stagedPath, full] of staged) fs.renameSync(stagedPath, full);
  } catch (err) {
    for (const [stagedPath] of staged) { try { fs.unlinkSync(stagedPath); } catch (_) { /* best effort */ } }
    for (const [full, text] of backups) fs.writeFileSync(full, text);
    return fail(REASON.ACCEPT_VERIFICATION_FAILED, `write failed, rolled back: ${err.message}`);
  }

  // Post-write self-check: the fingerprint sources.json now records must
  // equal actualNow, and must equal a fresh independent recomputation.
  let postCheck;
  try {
    postCheck = fp.checkFingerprint(root);
  } catch (err) {
    postCheck = { ok: false, reasonCode: err.reasonCode || "UNKNOWN_ERROR" };
  }
  if (!postCheck.ok || postCheck.actual !== actualNow) {
    for (const [full, text] of backups) fs.writeFileSync(full, text);
    return fail(REASON.ACCEPT_VERIFICATION_FAILED, `post-write check failed (${postCheck.reasonCode}), rolled back`);
  }

  process.stdout.write(`${JSON.stringify({ ok: true, reasonCode: REASON.ACCEPT_OK, fingerprint: actualNow, replacements: actualCounts })}\n`);
  console.log(`ACCEPT_OK fingerprint=${actualNow} replacements=${JSON.stringify(actualCounts)}`);
  process.exit(0);
}

function main() {
  const mode = process.argv[2];
  if (!new Set(["check", "review", "accept"]).has(mode)) return usageError(`unknown mode: ${mode}`);
  const rootFlagIdx = process.argv.indexOf("--root");
  const root = rootFlagIdx === -1 ? ROOT : path.resolve(process.argv[rootFlagIdx + 1]);
  const reviewFlagIdx = process.argv.indexOf("--review-path");
  const reviewPath = reviewFlagIdx === -1 ? path.join(root, "protocol", "generated", ".fingerprint-review.json") : path.resolve(process.argv[reviewFlagIdx + 1]);
  const ttlFlagIdx = process.argv.indexOf("--ttl-seconds");
  const ttlSeconds = ttlFlagIdx === -1 ? DEFAULT_REVIEW_TTL_SECONDS : Number(process.argv[ttlFlagIdx + 1]);
  if (ttlFlagIdx !== -1 && (!Number.isFinite(ttlSeconds) || ttlSeconds <= 0)) return usageError("--ttl-seconds must be a positive number");

  if (mode === "check") return modeCheck(root);
  if (mode === "review") return modeReview(root, reviewPath, ttlSeconds);
  return modeAccept(root, reviewPath);
}

main();
