#!/usr/bin/env node
/*
 * Read-cluster generator (clustered-read migration plan, M2).
 *
 *   node tools/protocol/generate_read_clusters.js          -- validate and regenerate
 *   node tools/protocol/generate_read_clusters.js --check  -- validate, regenerate in memory,
 *                                                            diff against disk; exit non-zero
 *                                                            on any error or drift, write nothing
 *   node tools/protocol/generate_read_clusters.js --root /tmp/copy
 *                                                          -- operate on an isolated tree
 *
 * Reads (never writes) protocol/read_clusters.canonical.json (hand-maintained)
 * and protocol/registers.canonical.json. Writes:
 *   protocol/generated/read_clusters.json      (audit/validation projection)
 *   protocol/generated/read_clusters_table.h   (constexpr cluster table for
 *                                               the scheduler and the servicer)
 *
 * Semantic rules (every violation is a named error; nothing is written):
 *   - every cluster is FC03, 1..operational_max_registers registers (the
 *     verified conservative operational maximum, not a protocol limit);
 *   - clusters and isolated reads never overlap each other;
 *   - every canonical register lies wholly inside exactly one cluster or one
 *     isolated read: no uncovered register, no register split by a boundary
 *     (multi-word straddle);
 *   - a register carrying a credential field (write_safety_class
 *     "credential") is only ever in an isolated read, and an isolated read
 *     holds only credential registers;
 *   - freshness_budget_ms = cadence_ms + J and active_freshness_budget_ms =
 *     active_cadence_ms + J, with J = (shortest cluster cadence) / 2;
 *   - sequence_after names an earlier cluster of the same role and cadence;
 *   - only settings clusters have an active cadence.
 * Canonical gap words (addresses inside a cluster that no register defines)
 * are listed per cluster; their content is unknown and never assumed zero.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { validate } = require("./lib/mini-schema");

function cliValue(flag) {
  const i = process.argv.indexOf(flag);
  return i === -1 ? null : process.argv[i + 1];
}
const ROOT = path.resolve(cliValue("--root") || path.join(__dirname, "..", ".."));
const CHECK_MODE = process.argv.includes("--check");
const sha256 = (s) => crypto.createHash("sha256").update(s, "utf8").digest("hex");
const hex4 = (n) => "0x" + n.toString(16).toUpperCase().padStart(4, "0");

const clusterSourcePath = path.join(ROOT, "protocol", "read_clusters.canonical.json");
const clusterSchemaPath = path.join(ROOT, "protocol", "schema", "read-clusters-source.schema.json");
const registerSourcePath = path.join(ROOT, "protocol", "registers.canonical.json");
const clusterRaw = fs.readFileSync(clusterSourcePath, "utf8");
const registerRaw = fs.readFileSync(registerSourcePath, "utf8");
const source = JSON.parse(clusterRaw);
const registers = JSON.parse(registerRaw).registers;
const HEADER = `Generated by tools/protocol/generate_read_clusters.js from protocol/read_clusters.canonical.json + protocol/registers.canonical.json. DO NOT EDIT BY HAND. clusters_hash=${sha256(clusterRaw).slice(0, 16)} canonical_hash=${sha256(registerRaw).slice(0, 16)}`;

const errors = [];
const fail = (code, message) => errors.push(`${code}: ${message}`);

// --- 1. Schema --------------------------------------------------------------
for (const e of validate(JSON.parse(fs.readFileSync(clusterSchemaPath, "utf8")), source)) {
  fail("READ_CLUSTERS_SCHEMA", `${e.path}: ${e.message}`);
}

// --- 2. Semantics -----------------------------------------------------------
const maxRegs = source.operational_max_registers;
const clusters = (source.clusters || []).map((c, index) => ({ ...c, index, a: parseInt(c.start, 16), n: c.register_count }));
const isolated = (source.isolated_reads || []).map((r) => ({ ...r, a: parseInt(r.start, 16), n: r.register_count }));
const endOf = (x) => x.a + 2 * x.n;  // exclusive; each 16-bit register = 2 address units

const ids = new Set();
for (const c of clusters) {
  if (ids.has(c.cluster_id)) fail("READ_CLUSTERS_DUPLICATE_ID", `cluster "${c.cluster_id}" is defined twice`);
  ids.add(c.cluster_id);
  if (!(c.n >= 1 && c.n <= maxRegs)) fail("READ_CLUSTERS_TOO_WIDE", `${c.cluster_id}: ${c.n} registers exceeds the operational maximum ${maxRegs}`);
  if (c.a % 2 !== 0) fail("READ_CLUSTERS_ODD_START", `${c.cluster_id}: start ${c.start} is not a register address`);
  if ((c.active_cadence_ms === null) !== (c.active_freshness_budget_ms === null)) {
    fail("READ_CLUSTERS_ACTIVE_PAIR", `${c.cluster_id}: active_cadence_ms and active_freshness_budget_ms must both be set or both null`);
  }
  if (c.active_cadence_ms !== null && c.role !== "settings") fail("READ_CLUSTERS_ACTIVE_ROLE", `${c.cluster_id}: only settings clusters have an active cadence`);
}
for (const r of isolated) {
  if (ids.has(r.read_id)) fail("READ_CLUSTERS_DUPLICATE_ID", `isolated read "${r.read_id}" reuses an id`);
  ids.add(r.read_id);
}
const cadences = clusters.flatMap((c) => [c.cadence_ms, c.active_cadence_ms]).filter((v) => typeof v === "number");
const J = cadences.length ? Math.min(...cadences) / 2 : 0;
for (const c of clusters) {
  if (c.freshness_budget_ms !== c.cadence_ms + J) {
    fail("READ_CLUSTERS_BUDGET", `${c.cluster_id}: freshness_budget_ms ${c.freshness_budget_ms} != cadence ${c.cadence_ms} + J ${J}`);
  }
  if (c.active_cadence_ms !== null && c.active_freshness_budget_ms !== c.active_cadence_ms + J) {
    fail("READ_CLUSTERS_BUDGET", `${c.cluster_id}: active_freshness_budget_ms ${c.active_freshness_budget_ms} != active cadence ${c.active_cadence_ms} + J ${J}`);
  }
  if (c.sequence_after !== null) {
    const lead = clusters.find((x) => x.cluster_id === c.sequence_after);
    if (!lead || lead.index >= c.index || lead.role !== c.role || lead.cadence_ms !== c.cadence_ms || lead.active_cadence_ms !== c.active_cadence_ms) {
      fail("READ_CLUSTERS_SEQUENCE", `${c.cluster_id}: sequence_after "${c.sequence_after}" must be an earlier cluster with the same role and cadence`);
    }
  }
}
const spans = [...clusters.map((c) => ({ id: c.cluster_id, a: c.a, n: c.n })), ...isolated.map((r) => ({ id: r.read_id, a: r.a, n: r.n }))];
for (let i = 0; i < spans.length; i++) {
  for (let j = i + 1; j < spans.length; j++) {
    if (spans[i].a < endOf(spans[j]) && spans[j].a < endOf(spans[i])) {
      fail("READ_CLUSTERS_OVERLAP", `${spans[i].id} ${hex4(spans[i].a)} x${spans[i].n} overlaps ${spans[j].id} ${hex4(spans[j].a)} x${spans[j].n}`);
    }
  }
}
const isCredential = (reg) => reg.fields.some((f) => f.write_safety_class === "credential");
const membership = new Map();  // register_id -> span id
for (const reg of registers) {
  const a = parseInt(reg.address, 16), e = a + 2 * reg.word_count;
  const holders = spans.filter((s) => a < endOf(s) && s.a < e);
  const wholly = holders.filter((s) => a >= s.a && e <= endOf(s));
  if (holders.length === 0) { fail("READ_CLUSTERS_UNCOVERED", `${reg.address} ${reg.register_id} is in no cluster or isolated read`); continue; }
  if (wholly.length !== 1 || holders.length !== 1) {
    fail("READ_CLUSTERS_STRADDLE", `${reg.address} ${reg.register_id} (${reg.word_count} words) is split by a boundary of ${holders.map((h) => h.id).join("/")}`);
    continue;
  }
  const holder = wholly[0];
  const inIsolated = isolated.some((r) => r.read_id === holder.id);
  if (isCredential(reg) && !inIsolated) fail("READ_CLUSTERS_CREDENTIAL", `${reg.address} ${reg.register_id} is a credential register inside cluster ${holder.id}`);
  if (!isCredential(reg) && inIsolated) fail("READ_CLUSTERS_ISOLATED_NON_CREDENTIAL", `${reg.address} ${reg.register_id} is not a credential but sits in isolated read ${holder.id}`);
  if (reg.read_function !== "read_holding_registers_fc03") fail("READ_CLUSTERS_FUNCTION", `${reg.address} ${reg.register_id} is not an FC03 register`);
  membership.set(reg.register_id, holder.id);
}
for (const r of isolated) {
  if (!registers.some((reg) => membership.get(reg.register_id) === r.read_id)) fail("READ_CLUSTERS_EMPTY_ISOLATED", `isolated read ${r.read_id} holds no register`);
}

if (errors.length) {
  for (const e of errors) console.error(e);
  console.error(`generate_read_clusters.js: ${errors.length} error(s); nothing written.`);
  process.exit(1);
}

// --- 3. Projection ----------------------------------------------------------
const definedWords = new Set();
for (const reg of registers) for (let i = 0; i < reg.word_count; i++) definedWords.add(parseInt(reg.address, 16) + 2 * i);
const projected = clusters.map((c) => {
  const regs = registers.filter((reg) => membership.get(reg.register_id) === c.cluster_id).sort((x, y) => parseInt(x.address, 16) - parseInt(y.address, 16));
  const gaps = [];
  for (let w = c.a; w < endOf(c); w += 2) if (!definedWords.has(w)) gaps.push(hex4(w));
  return {
    cluster_id: c.cluster_id, role: c.role, start: hex4(c.a), end_inclusive: hex4(endOf(c) - 2), register_count: c.n, payload_bytes: 2 * c.n,
    cadence_ms: c.cadence_ms, active_cadence_ms: c.active_cadence_ms, phase_ms: c.phase_ms,
    freshness_budget_ms: c.freshness_budget_ms, active_freshness_budget_ms: c.active_freshness_budget_ms,
    sequence_after: c.sequence_after, register_ids: regs.map((r) => r.register_id), gap_words: gaps,
    hardware_evidence: c.hardware_evidence,
  };
});
const projectedIsolated = isolated.map((r) => ({
  read_id: r.read_id, start: hex4(r.a), register_count: r.n, payload_bytes: 2 * r.n, trigger: r.trigger,
  register_ids: registers.filter((reg) => membership.get(reg.register_id) === r.read_id).map((reg) => reg.register_id),
}));
const json = JSON.stringify({
  $comment: "Generated -- do not edit. Edit protocol/read_clusters.canonical.json and run `node tools/protocol/generate_read_clusters.js`.",
  $generated_by: HEADER,
  operational_max_registers: maxRegs,
  scheduling_allowance_ms: J,
  cluster_count: projected.length,
  covered_register_count: registers.filter((reg) => clusters.some((c) => membership.get(reg.register_id) === c.cluster_id)).length,
  isolated_register_count: registers.filter((reg) => isolated.some((r) => membership.get(reg.register_id) === r.read_id)).length,
  clusters: projected,
  isolated_reads: projectedIsolated,
}, null, 2) + "\n";

const roleEnum = { telemetry: "TELEMETRY", settings: "SETTINGS", static: "STATIC" };
const L = [];
L.push("#pragma once");
L.push(`// ${HEADER}`);
L.push("// Cluster table for the clustered read path (plan M2). Geometry is the");
L.push("// hardware-verified conservative operational geometry (gate A, 2026-09-28);");
L.push("// operational_max_registers is a design limit, not the BMS protocol limit.");
L.push("#include <cstddef>");
L.push("#include <cstdint>");
L.push("");
L.push("namespace jk_read_clusters {");
L.push("");
L.push("enum class Role : uint8_t { TELEMETRY = 0, SETTINGS = 1, STATIC = 2 };");
L.push("constexpr uint32_t kNoCadence = 0;  // no active cadence");
L.push("constexpr int kNoCluster = -1;");
L.push("");
L.push("struct Cluster {");
L.push("  const char *id;");
L.push("  Role role;");
L.push("  uint16_t start;             // first register address (2 address units per register)");
L.push("  uint16_t register_count;    // FC03 quantity");
L.push("  uint16_t payload_bytes;     // exact expected data bytes = 2 * register_count");
L.push("  uint32_t cadence_ms;        // normal cadence");
L.push("  uint32_t active_cadence_ms; // cadence under the active Settings lease, or kNoCadence");
L.push("  uint32_t phase_ms;          // offset from the telemetry cycle");
L.push("  uint32_t freshness_budget_ms;");
L.push("  uint32_t active_freshness_budget_ms;  // or kNoCadence");
L.push("  int sequence_after;         // index of the cluster this one follows in the same cycle, or kNoCluster");
L.push("};");
L.push("");
L.push(`constexpr uint16_t kOperationalMaxRegisters = ${maxRegs};`);
L.push(`constexpr uint32_t kSchedulingAllowanceMs = ${J};`);
L.push("constexpr Cluster kClusters[] = {");
for (const c of projected) {
  const seq = c.sequence_after === null ? "kNoCluster" : String(projected.findIndex((x) => x.cluster_id === c.sequence_after));
  L.push(`    {"${c.cluster_id}", Role::${roleEnum[c.role]}, ${c.start}, ${c.register_count}, ${c.payload_bytes}, ${c.cadence_ms}, ` +
    `${c.active_cadence_ms === null ? "kNoCadence" : c.active_cadence_ms}, ${c.phase_ms}, ${c.freshness_budget_ms}, ` +
    `${c.active_freshness_budget_ms === null ? "kNoCadence" : c.active_freshness_budget_ms}, ${seq}},`);
}
L.push("};");
L.push("constexpr std::size_t kClusterCount = sizeof(kClusters) / sizeof(kClusters[0]);");
L.push(`constexpr uint16_t kMaxClusterPayloadBytes = ${Math.max(...projected.map((c) => c.payload_bytes))};`);
L.push("");
L.push("// Isolated reads: never part of a cluster, a cluster cache, state, diagnostics or logs.");
L.push("struct IsolatedRead { const char *id; uint16_t start; uint16_t register_count; };");
L.push("constexpr IsolatedRead kIsolatedReads[] = {");
for (const r of projectedIsolated) L.push(`    {"${r.read_id}", ${r.start}, ${r.register_count}},`);
L.push("};");
L.push("constexpr std::size_t kIsolatedReadCount = sizeof(kIsolatedReads) / sizeof(kIsolatedReads[0]);");
L.push("");
L.push("constexpr bool overlaps(uint16_t a, uint16_t n, uint16_t b, uint16_t m) {");
L.push("  return uint32_t(a) < uint32_t(b) + 2U * m && uint32_t(b) < uint32_t(a) + 2U * n;");
L.push("}");
L.push("constexpr bool table_is_valid() {");
L.push("  for (std::size_t i = 0; i < kClusterCount; i++) {");
L.push("    const Cluster &c = kClusters[i];");
L.push("    if (c.register_count < 1 || c.register_count > kOperationalMaxRegisters || c.payload_bytes != 2U * c.register_count) return false;");
L.push("    if (c.payload_bytes > kMaxClusterPayloadBytes) return false;");
L.push("    for (std::size_t j = 0; j < kIsolatedReadCount; j++)");
L.push("      if (overlaps(c.start, c.register_count, kIsolatedReads[j].start, kIsolatedReads[j].register_count)) return false;");
L.push("    for (std::size_t j = 0; j < i; j++)");
L.push("      if (overlaps(c.start, c.register_count, kClusters[j].start, kClusters[j].register_count)) return false;");
L.push("  }");
L.push("  return true;");
L.push("}");
L.push('static_assert(table_is_valid(), "cluster table: size, overlap or credential-isolation violation");');
L.push("");
L.push("// Index of the cluster containing register address `address`, or kNoCluster.");
L.push("constexpr int cluster_of(uint16_t address) {");
L.push("  for (std::size_t i = 0; i < kClusterCount; i++)");
L.push("    if (address >= kClusters[i].start && uint32_t(address) < uint32_t(kClusters[i].start) + 2U * kClusters[i].register_count) return int(i);");
L.push("  return kNoCluster;");
L.push("}");
L.push("");
L.push("}  // namespace jk_read_clusters");
const header = L.join("\n") + "\n";

// --- 4. Write or check --------------------------------------------------------
const outputs = {
  [path.join(ROOT, "protocol", "generated", "read_clusters.json")]: json,
  [path.join(ROOT, "protocol", "generated", "read_clusters_table.h")]: header,
};
if (CHECK_MODE) {
  const stale = Object.entries(outputs).filter(([t, c]) => !fs.existsSync(t) || fs.readFileSync(t, "utf8") !== c);
  for (const [t] of stale) console.log(`DRIFT  ${path.relative(ROOT, t)}`);
  if (stale.length) {
    console.log("generate_read_clusters.js --check: artifact(s) out of date. Run 'node tools/protocol/generate_read_clusters.js' to regenerate.");
    process.exit(1);
  }
  console.log(`generate_read_clusters.js --check: no drift. ${projected.length} clusters, ${projectedIsolated.length} isolated read(s), every canonical register covered exactly once.`);
  process.exit(0);
}
for (const [target, content] of Object.entries(outputs)) {
  const tmp = `${target}.tmp-${process.pid}`;
  fs.writeFileSync(tmp, content, "utf8");
  fs.renameSync(tmp, target);
  console.log(`wrote ${path.relative(ROOT, target)}`);
}
