#!/usr/bin/env node
/*
 * Protocol catalog generator (Stage 1, spec section 9).
 *
 *   node tools/protocol/generate.js          — regenerate every derived artifact
 *   node tools/protocol/generate.js --check  — regenerate in memory and diff
 *                                               against what's on disk; exit
 *                                               non-zero on any drift, without
 *                                               writing anything
 *   node tools/protocol/generate.js --root /tmp/copy
 *                                             — operate on an isolated tree
 *
 * Reads (never writes) the two hand-maintained canonical sources:
 *   protocol/registers.canonical.json
 *   protocol/non_register_entities.canonical.json
 *
 * Writes (only in normal mode, and only if canonical validation passes —
 * spec: "invalid canonical source не генерує часткові outputs"):
 *   register_catalog.json                        (backward-compatible location/shape)
 *   protocol/generated/coverage_report.md
 *   jk_bms.js's own GENERATED PROTOCOL CATALOG block (in place, between the
 *     BEGIN/END markers already present in the file)
 *
 * Every generated artifact's header carries the canonical source's own
 * catalog_version and a content hash (sha256 of the two canonical JSON
 * files) instead of a wall-clock timestamp or absolute path, so two
 * consecutive runs on the same input are byte-identical (spec section 9).
 */
"use strict";

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

function cliValue(flag) {
  const i = process.argv.indexOf(flag);
  return i === -1 ? null : process.argv[i + 1];
}
const ROOT = path.resolve(cliValue("--root") || path.join(__dirname, "..", ".."));
const mini = require("./lib/mini-schema.js");
const semantic = require("./lib/semantic-checks.js");
const { computeReleaseGenerationId } = require("./lib/release-id.js");

const CHECK_MODE = process.argv.includes("--check");

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function sha256(str) {
  return crypto.createHash("sha256").update(str, "utf8").digest("hex");
}

function atomicWrite(targetPath, content) {
  const dir = path.dirname(targetPath);
  const tmp = path.join(dir, `.${path.basename(targetPath)}.tmp-${process.pid}`);
  fs.writeFileSync(tmp, content, "utf8");
  fs.renameSync(tmp, targetPath);
}

// ---------------------------------------------------------------------------
// Load + validate canonical sources
// ---------------------------------------------------------------------------
const registerSourcePath = path.join(ROOT, "protocol", "registers.canonical.json");
const nonRegisterSourcePath = path.join(ROOT, "protocol", "non_register_entities.canonical.json");
const registerSourceRaw = fs.readFileSync(registerSourcePath, "utf8");
const nonRegisterSourceRaw = fs.readFileSync(nonRegisterSourcePath, "utf8");
const registerDoc = JSON.parse(registerSourceRaw);
const nonRegisterDoc = JSON.parse(nonRegisterSourceRaw);

const registerSchema = readJson(path.join(ROOT, "protocol", "schema", "register-source.schema.json"));
const nonRegisterSchema = readJson(path.join(ROOT, "protocol", "schema", "non-register-source.schema.json"));

const schemaErrors = [
  ...mini.validate(registerSchema, registerDoc).map((e) => ({ ...e, path: `registers.canonical.json:${e.path}` })),
  ...mini.validate(nonRegisterSchema, nonRegisterDoc).map((e) => ({ ...e, path: `non_register_entities.canonical.json:${e.path}` })),
];
const semanticErrors = semantic.check(registerDoc, nonRegisterDoc, ROOT);

if (schemaErrors.length || semanticErrors.length) {
  console.log(`Canonical source is INVALID — refusing to generate anything (spec: no partial outputs).`);
  console.log(`Schema errors: ${schemaErrors.length}`);
  schemaErrors.forEach((e) => console.log(`  SCHEMA  ${e.path}  ${e.message}`));
  console.log(`Semantic errors: ${semanticErrors.length}`);
  semanticErrors.forEach((e) => console.log(`  ${e.code}  ${e.path}  ${e.message}`));
  process.exit(1);
}

const canonicalHash = sha256(registerSourceRaw + "\0" + nonRegisterSourceRaw).slice(0, 16);
const catalogVersion = registerDoc.catalog_version;
const HEADER = `Generated by tools/protocol/generate.js from protocol/registers.canonical.json + protocol/non_register_entities.canonical.json. DO NOT EDIT BY HAND. catalog_version=${catalogVersion} source_hash=${canonicalHash}`;

// Shared release_generation_id (Stage 1 corrective pass, Work 7): derived
// purely from immutable inputs (see tools/protocol/lib/release-id.js), so
// computing it here never creates a circular dependency on this file's own
// output. If sources.json is missing an expected evidence entry (e.g. an
// intentionally minimal test sandbox that doesn't need this id), that is
// reported with the same stable reasonCode convention as the rest of the
// fingerprint tooling, not a raw stack trace.
let releaseGenerationId;
try {
  releaseGenerationId = computeReleaseGenerationId(ROOT);
} catch (err) {
  console.error(`${err.reasonCode || "RELEASE_GENERATION_ID_COMPUTE_FAILED"}: ${err.message}`);
  process.exit(1);
}

// Flatten for convenience.
const allRegisterFields = []; // {field, register}
for (const reg of registerDoc.registers) {
  for (const f of reg.fields) allRegisterFields.push({ field: f, register: reg });
}
// Deterministic order: registers.canonical.json is already address-sorted
// (tools/protocol/authoring/build_seed.py sorts it); fields within a
// register keep their declared array order. No object-key iteration is
// relied upon anywhere below for ordering.

// ---------------------------------------------------------------------------
// 1. register_catalog.json — backward-compatible location and shape.
// ---------------------------------------------------------------------------
function buildRegisterCatalog() {
  const rows = [];
  for (const { field: f, register: r } of allRegisterFields) {
    const row = {
      key: f.key,
      domain: f.esphome_domain,
      address: r.address,
      width: r.register_width_bits,
      signed: f.signedness === "signed",
      access: f.access,
      effective_access: f.effective_access,
      scale: f.scale,
      unit: f.canonical_unit,
      min: f.minimum,
      max: f.maximum,
      step: f.step,
      editor: f.editor_kind,
      // manager now derives from effective_access (Крок G.2/H: "mock генерує
      // metadata для... не лише generic RW addresses" + must not offer write
      // simulation for a field whose real write path was removed).
      manager:
        f.write_safety_class === "topology" ? "bespoke_topology" :
        f.write_safety_class === "credential" ? "bespoke_passcode" :
        f.effective_access === "rw" ? "generic" : "readonly",
      verification_status: f.verification_status,
      note: r.safety_notes || undefined,
    };
    if (f.packed_siblings.length === 1) row.packed_with = f.packed_siblings[0];
    else if (f.packed_siblings.length > 1) row.packed_with_group = f.packed_siblings;
    if (f.enum_map && f.esphome_domain === "select") {
      row.options = Object.values(f.enum_map);
    }
    // undefined values are dropped by JSON.stringify — keep the object tidy
    // rather than emitting explicit nulls for optional documentary fields.
    Object.keys(row).forEach((k) => row[k] === undefined && delete row[k]);
    rows.push(row);
  }
  return {
    "$comment": "GENERATED — single source of truth for every JK BMS Modbus register this project's UI exposes. " +
      "DO NOT EDIT BY HAND. Edit protocol/registers.canonical.json and run `node tools/protocol/generate.js` instead.",
    "$generated_by": HEADER,
    "release_generation_id": releaseGenerationId,
    "registers": rows,
  };
}

// ---------------------------------------------------------------------------
// 2. GENERIC_TX_ADDRESS / NON_REGISTER_ENTITY_IDS for jk_bms.js injection.
//
// GENERIC_TX_ADDRESS reflects CURRENT WIRE BEHAVIOR (which addresses the
// generic write-transaction manager in the deployed firmware actually
// services today) — it is generated from DECLARED access, not
// effective_access, because Stage 1 must not change wire write behavior
// (spec section 4/11). effective_access is still carried into
// register_catalog.json for the next stage's transaction core to consult.
// ---------------------------------------------------------------------------
function buildGenericTxAddress() {
  // Stage 1 Remediation (CODEX_STAGE_1_REVIEW.md P0-4 / Крок G.2): this
  // list is now gated on effective_access === "rw" — the catalog's actual
  // write-safety POLICY output — not merely declared access. A field whose
  // enum semantics or dynamic unit dependency is unresolved (effective_access
  // "r") is excluded here even if the underlying ESPHome entity still
  // formally exists; batterylifepo4.yaml's own set_action for those exact
  // entities has ALSO been removed (see the register's safety_notes), so
  // there is no remaining path — UI, direct HTTP, or JS — that can turn a
  // write attempt on one of them into a real Modbus command.
  const entries = [];
  for (const { field: f, register: r } of allRegisterFields) {
    if (f.effective_access !== "rw") continue;
    if (f.write_safety_class === "topology" || f.write_safety_class === "credential") continue;
    if (!f.esphome_write_entity_id) continue;
    entries.push([f.key, r.address]);
  }
  return entries;
}

function buildBlockedWriteKeys() {
  // Declared rw but NOT effective rw — the frontend needs this list to
  // render a read-only reason (Крок G.7) instead of a misleading editable
  // input for a field whose write path has been removed at the firmware
  // level.
  const entries = [];
  for (const { field: f } of allRegisterFields) {
    if (f.access === "rw" && f.effective_access !== "rw") {
      entries.push({
        key: f.key,
        reason: f.dynamic_dependency ? f.dynamic_dependency.rule : "verification_status " + f.verification_status,
      });
    }
  }
  return entries;
}

function buildNonRegisterKeys() {
  return nonRegisterDoc.entities.map((e) => e.key);
}

// Stage 5 ("Виправити фундамент читання"): the canonical source already
// carries the authoritative unit/precision/bounds/poll-tier metadata per
// field, but none of it previously reached the browser — jk_bms.js
// instead re-typed unit/min/max/step literals by hand in half a dozen
// separate tables (diagnosticUnit(), SETTING_DEFS, UK_UNIT_MAP,
// UNIT_DISPLAY, per-bindText() call sites), none kept in sync by any
// generator. This is the single source those tables should read from.
// Note: this project's frontend has no client-side polling loop — all
// live values arrive over one SSE channel pushed by the firmware, so
// pollGroup/freshnessBudgetS are consumed by jk_bms.js purely to judge
// per-parameter staleness against the time since the last SSE update for
// that key, not to drive a fetch interval.
function buildFieldMeta() {
  const entries = [];
  for (const { field: f, register: r } of allRegisterFields) {
    entries.push([f.key, {
      unit: f.canonical_unit ?? null,
      ukUnit: f.uk_display_unit ?? null,
      enUnit: f.en_display_unit ?? null,
      precision: f.decimal_precision ?? null,
      min: f.minimum ?? null,
      max: f.maximum ?? null,
      step: f.step ?? null,
      pollGroup: r.poll_group ?? null,
      freshnessBudgetS: r.freshness_budget_s ?? null,
      // Final-preparation-plan Stage 1: the fields below already existed in
      // protocol/registers.canonical.json but never reached the browser —
      // jk_bms.js rendered Settings from 3 separate, generator-disconnected
      // hand-typed arrays instead (SETTING_DEFS/DIAGNOSTIC_ENTITY_ORDER/
      // DIAGNOSTIC_ENTITY_LABELS), which already caused one real drift bug
      // (discharge_ocpr_left/discharge_scpr_left misspelled in 3 of 4 of
      // them). This is the single generated source those hand arrays are
      // being retired in favor of — see jk_bms.js's own comment at the
      // fieldMeta consumption site.
      labelUk: f.frontend_label_uk ?? null,
      labelEn: f.frontend_label_en ?? null,
      uiSection: f.ui_section ?? null,
      uiOrder: f.ui_order ?? null,
      uiGroup: f.ui_group ?? null,
      editorKind: f.editor_kind ?? null,
      enumMap: f.enum_map ?? null,
    }]);
  }
  // Self-audit (2026-09-11): the first version of this function covered
  // only real registers, so jk_bms.js's diagnosticUnit() kept a ~47-entry
  // hand-typed fallback table "for computed entities" — but most of that
  // table's entries WERE real registers (shadowed, dead code) and the
  // handful of genuinely computed entities it still served
  // (total_voltage, current, ...) have their own authoritative unit data
  // right here in non_register_entities.canonical.json, just never
  // included. Folding it in makes fieldMeta cover every entity this
  // project knows about, leaving nothing left to hand-maintain.
  const registerFreshnessByKey = new Map(
    allRegisterFields.map(({ field: f, register: r }) => [f.key, { pollGroup: r.poll_group ?? null, freshnessBudgetS: r.freshness_budget_s ?? null }])
  );
  for (const e of nonRegisterDoc.entities) {
    // Stage 5 follow-up (2026-09-11): a computed entity that is a direct,
    // same-read derivation of exactly one real register (e.g.
    // total_voltage from total_voltage_raw) inherits that register's
    // poll_group/freshness_budget_s instead of being permanently
    // un-stale-able — otherwise the Overview panel's most prominent
    // values (voltage/current) would never show a freshness marker no
    // matter how long the underlying register actually went silent.
    let derivedFreshness = { pollGroup: null, freshnessBudgetS: null };
    if (e.derived_from_register_key) {
      const source = registerFreshnessByKey.get(e.derived_from_register_key);
      if (!source) {
        throw new Error(`NON_REGISTER_DERIVED_FROM_UNKNOWN_REGISTER_KEY: "${e.key}".derived_from_register_key = "${e.derived_from_register_key}" is not a real register field key`);
      }
      derivedFreshness = source;
    }
    entries.push([e.key, {
      unit: e.unit ?? null,
      ukUnit: e.uk_display_unit ?? null,
      enUnit: e.en_display_unit ?? null,
      precision: null,
      min: null,
      max: null,
      step: null,
      pollGroup: derivedFreshness.pollGroup,
      freshnessBudgetS: derivedFreshness.freshnessBudgetS,
      // non_register_entities.canonical.json already carries labels (its
      // own schema has frontend_label_uk/en) — piped through for the same
      // reason register fields' labels are, so nothing needs a second,
      // hand-typed label table. It has no ui_section/ui_order/ui_group/
      // editor_kind/enum_map concept of its own (a different, simpler
      // "category" field instead) — those stay null here, matching how
      // DIAGNOSTIC_ENTITY_LABELS/ORDER's replacement is scoped to
      // register-backed rows only (isBmsRegisterEntry in jk_bms.js).
      labelUk: e.frontend_label_uk ?? null,
      labelEn: e.frontend_label_en ?? null,
      uiSection: null,
      uiOrder: null,
      uiGroup: null,
      editorKind: null,
      enumMap: null,
    }]);
  }
  return entries;
}

// ---------------------------------------------------------------------------
// 3. C++ metadata header (unwired — see module comment above).
// ---------------------------------------------------------------------------
function cEscape(s) {
  return String(s == null ? "" : s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function buildCppHeader() {
  const lines = [];
  lines.push("// " + HEADER.replace(/\n/g, " "));
  lines.push("//");
  lines.push("// Prepared for a LATER stage's C++ transaction core (roadmap Stage 2/6). Stage 1");
  lines.push("// intentionally does NOT #include this header from batterylifepo4.yaml or any");
  lines.push("// other build target — doing so would pull generated metadata into the actual");
  lines.push("// firmware image, which is out of Stage 1's boundary (\"не перебудовуй transaction");
  lines.push("// manager\", \"Stage 1 не повинен змінювати wire write behavior\"). See");
  lines.push("// docs/adr/0001-protocol-catalog.md for the RAM/flash-impact reasoning.");
  lines.push("#pragma once");
  lines.push("#include <cstddef>");
  lines.push("#include <cstdint>");
  lines.push("");
  lines.push("namespace jk_protocol_catalog {");
  lines.push("");
  lines.push("enum class Access : uint8_t { R = 0, RW = 1, UNSUPPORTED = 2 };");
  lines.push("enum class WireType : uint8_t { U8, S8, U16, S16, U32, S32, F32, ASCII, BIT };");
  lines.push("");
  lines.push("struct FieldMetadata {");
  lines.push("  const char *key;");
  lines.push("  uint16_t address;");
  lines.push("  uint8_t field_width_bits;");
  lines.push("  uint32_t mask;");
  lines.push("  uint8_t shift;");
  lines.push("  bool is_signed;");
  lines.push("  WireType wire_type;");
  lines.push("  float scale;");
  lines.push("  float offset;");
  lines.push("  Access declared_access;");
  lines.push("  Access effective_access;");
  lines.push("};");
  lines.push("");
  lines.push(`constexpr std::size_t kFieldCount = ${allRegisterFields.length};`);
  lines.push("constexpr FieldMetadata kFields[kFieldCount] = {");
  const wireTypeMap = { U8: "WireType::U8", S8: "WireType::S8", U16: "WireType::U16", S16: "WireType::S16",
    U32: "WireType::U32", S32: "WireType::S32", F32: "WireType::F32", ASCII: "WireType::ASCII", BIT: "WireType::BIT" };
  const accessMap = { r: "Access::R", rw: "Access::RW", unsupported: "Access::UNSUPPORTED" };
  // C++ float literals need a decimal point (e.g. "1.0f", not the invalid
  // "1f"/"0f" octal-looking token JS's plain `${n}f` would produce for
  // whole numbers such as scale=1 or offset=0).
  const cFloat = (n) => (Number.isInteger(n) ? `${n}.0f` : `${n}f`);
  for (const { field: f, register: r } of allRegisterFields) {
    const maskLiteral = f.mask ? f.mask : "0x0";
    lines.push(
      `    {"${cEscape(f.key)}", ${r.address}, ${f.field_width_bits}, ${maskLiteral}, ${f.shift || 0}, ` +
      `${f.signedness === "signed" ? "true" : "false"}, ${wireTypeMap[f.wire_type]}, ${cFloat(f.scale)}, ${cFloat(f.offset)}, ` +
      `${accessMap[f.access]}, ${accessMap[f.effective_access]}},`
    );
  }
  lines.push("};");
  lines.push("");
  lines.push("} // namespace jk_protocol_catalog");
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// 5. Coverage / evidence report (human-readable).
// ---------------------------------------------------------------------------
function buildCoverageReport() {
  const byStatus = {};
  for (const { field: f } of allRegisterFields) byStatus[f.verification_status] = (byStatus[f.verification_status] || 0) + 1;
  const rCount = allRegisterFields.filter((x) => x.field.access === "r").length;
  const rwCount = allRegisterFields.filter((x) => x.field.access === "rw").length;
  const effRw = allRegisterFields.filter((x) => x.field.effective_access === "rw").length;
  const effR = allRegisterFields.filter((x) => x.field.effective_access === "r").length;
  const effUnsupported = allRegisterFields.filter((x) => x.field.effective_access === "unsupported").length;
  const packedRegisters = registerDoc.registers.filter((r) => r.fields.length > 1);

  const lines = [];
  lines.push("# Protocol catalog coverage / evidence report");
  lines.push("");
  lines.push(`_${HEADER}_`);
  lines.push("");
  lines.push(`Release generation id: \`${releaseGenerationId}\``);
  lines.push("");
  lines.push("## Counts");
  lines.push("");
  lines.push(`- Physical registers: ${registerDoc.registers.length}`);
  lines.push(`- Logical fields: ${allRegisterFields.length}`);
  lines.push(`- Declared access R: ${rCount}, RW: ${rwCount}`);
  lines.push(`- Effective access RW: ${effRw}, R: ${effR}, unsupported: ${effUnsupported}`);
  lines.push(`- Packed registers (>1 logical field): ${packedRegisters.length}`);
  lines.push(`- Non-register entities: ${nonRegisterDoc.entities.length}`);
  lines.push("");
  lines.push("## Verification status breakdown");
  lines.push("");
  lines.push("| Status | Field count |");
  lines.push("|---|---:|");
  for (const [status, count] of Object.entries(byStatus).sort()) lines.push(`| ${status} | ${count} |`);
  lines.push("");
  lines.push("## Full field-level evidence coverage matrix");
  lines.push("");
  lines.push("| key | address | mask/shift | access | effective | scale | unit | verification_status | evidence sources |");
  lines.push("|---|---|---|---|---|---|---|---|---|");
  for (const { field: f, register: r } of allRegisterFields) {
    const maskShift = f.mask ? `${f.mask}/${f.shift || 0}` : "(full word)";
    const sources = f.evidence.map((e) => e.source_id).join(", ");
    lines.push(`| ${f.key} | ${r.address} | ${maskShift} | ${f.access} | ${f.effective_access} | ${f.scale} | ${f.canonical_unit || "—"} | ${f.verification_status} | ${sources} |`);
  }
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// 6. jk_bms.js injection.
// ---------------------------------------------------------------------------
const JS_BEGIN = "  // >>> BEGIN GENERATED PROTOCOL CATALOG (Stage 1, IMPLEMENTATION_ROADMAP.md) — DO NOT EDIT BY HAND.";
const JS_END = "  // <<< END GENERATED PROTOCOL CATALOG";

function buildJsInjectionBlock() {
  const txEntries = buildGenericTxAddress();
  const nonRegKeys = buildNonRegisterKeys();
  const blockedKeys = buildBlockedWriteKeys();
  const fieldMetaEntries = buildFieldMeta();
  const fmtHex = (addr) => addr; // already "0xNNNN" string form in canonical source
  const txLines = txEntries.map(([k, addr]) => `      ${k}: ${fmtHex(addr)},`).join("\n");
  const nrLines = [];
  for (let i = 0; i < nonRegKeys.length; i += 4) {
    nrLines.push("      " + nonRegKeys.slice(i, i + 4).map((k) => `"${k}",`).join(" "));
  }
  const jsStringEscape = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const blockedLines = blockedKeys
    .map((b) => `      ${b.key}: "${jsStringEscape(b.reason)}",`)
    .join("\n");
  const jsLiteral = (v) => (v === null || v === undefined ? "null" : typeof v === "string" ? `"${jsStringEscape(v)}"` : String(v));
  // enum_map is the one non-scalar fieldMeta value (an object, e.g.
  // {"0":"Off","1":"On"}) — jsLiteral only handles null/string/number, so
  // it gets its own small object-literal serializer, keys sorted for
  // deterministic output (this project's generate.js --check drift
  // detection depends on byte-identical regeneration).
  const jsEnumMapLiteral = (m) => {
    if (m === null || m === undefined) return "null";
    const keys = Object.keys(m).sort();
    return `Object.freeze({ ${keys.map((k) => `"${jsStringEscape(k)}": "${jsStringEscape(m[k])}"`).join(", ")} })`;
  };
  const fieldMetaLines = fieldMetaEntries
    .map(([k, m]) => `      ${k}: { unit: ${jsLiteral(m.unit)}, ukUnit: ${jsLiteral(m.ukUnit)}, enUnit: ${jsLiteral(m.enUnit)}, precision: ${jsLiteral(m.precision)}, min: ${jsLiteral(m.min)}, max: ${jsLiteral(m.max)}, step: ${jsLiteral(m.step)}, pollGroup: ${jsLiteral(m.pollGroup)}, freshnessBudgetS: ${jsLiteral(m.freshnessBudgetS)}, labelUk: ${jsLiteral(m.labelUk)}, labelEn: ${jsLiteral(m.labelEn)}, uiSection: ${jsLiteral(m.uiSection)}, uiOrder: ${jsLiteral(m.uiOrder)}, uiGroup: ${jsLiteral(m.uiGroup)}, editorKind: ${jsLiteral(m.editorKind)}, enumMap: ${jsEnumMapLiteral(m.enumMap)} },`)
    .join("\n");
  return [
    JS_BEGIN,
    "  // Regenerate with: node tools/protocol/generate.js",
    "  // Source of truth: protocol/registers.canonical.json + protocol/non_register_entities.canonical.json",
    "  // `node tools/protocol/generate.js --check` fails if this block drifts from that source.",
    `  // ${HEADER}`,
    "  const PROTOCOL_CATALOG = Object.freeze({",
    `    releaseGenerationId: "${releaseGenerationId}",`,
    "    genericTxAddress: Object.freeze({",
    txLines,
    "    }),",
    "    nonRegisterKeys: Object.freeze([",
    nrLines.join("\n"),
    "    ]),",
    "    // Declared rw in the ESPHome entity, but effective_access is \"r\": the write path was REMOVED from",
    "    // batterylifepo4.yaml (Stage 1 Remediation, Крок G). The Settings UI renders these read-only with",
    "    // this reason instead of an editable input.",
    "    blockedWriteKeys: Object.freeze({",
    blockedLines,
    "    }),",
    "    // Stage 5: authoritative per-field unit/precision/bounds/poll-tier",
    "    // metadata, sourced from protocol/registers.canonical.json — the single",
    "    // place unit/min/max/step/freshness data should be read from, replacing",
    "    // the hand-maintained tables this project previously duplicated it into.",
    "    fieldMeta: Object.freeze({",
    fieldMetaLines,
    "    }),",
    "  });",
    JS_END,
  ].join("\n");
}

function injectIntoJkBmsJs(currentSource) {
  const beginIdx = currentSource.indexOf(JS_BEGIN);
  const endIdx = currentSource.indexOf(JS_END);
  if (beginIdx === -1 || endIdx === -1) {
    throw new Error(
      "jk_bms.js is missing the GENERATED PROTOCOL CATALOG markers. This generator only ever REPLACES the " +
      "content between an existing BEGIN/END marker pair (a deliberate one-time manual edit) — it does not " +
      "insert new markers itself."
    );
  }
  const endOfEndLine = currentSource.indexOf("\n", endIdx);
  const before = currentSource.slice(0, beginIdx);
  const after = currentSource.slice(endOfEndLine);
  return before + buildJsInjectionBlock() + after;
}

// ---------------------------------------------------------------------------
// Compute everything, then either write (normal mode) or diff (--check).
// ---------------------------------------------------------------------------
const outputs = {
  [path.join(ROOT, "register_catalog.json")]: JSON.stringify(buildRegisterCatalog(), null, 2) + "\n",
  [path.join(ROOT, "protocol", "generated", "coverage_report.md")]: buildCoverageReport(),
};

const jkBmsJsPath = path.join(ROOT, "jk_bms.js");
const currentJkBmsJs = fs.readFileSync(jkBmsJsPath, "utf8");
const newJkBmsJs = injectIntoJkBmsJs(currentJkBmsJs);
const generatedJsBlock = buildJsInjectionBlock();

const MANIFEST_PATH = path.join(ROOT, "protocol", "generated", ".generation-manifest.json");

// A deterministic generation_id derived from content only (canonicalHash +
// the exact set of output hashes) — NOT a random UUID or timestamp, so two
// runs on the same input produce the SAME manifest (spec Крок K.5: "два
// послідовні generation runs мають давати byte-identical output").
function buildManifest() {
  const fileHashes = {};
  for (const target of Object.keys(outputs)) fileHashes[path.relative(ROOT, target)] = sha256(outputs[target]);
  fileHashes["jk_bms.js#generated_protocol_catalog_block"] = sha256(generatedJsBlock);
  const generationId = sha256(canonicalHash + JSON.stringify(fileHashes)).slice(0, 16);
  return {
    generation_id: generationId,
    release_generation_id: releaseGenerationId,
    catalog_version: catalogVersion,
    source_hash: canonicalHash,
    file_hashes: fileHashes,
  };
}
const manifest = buildManifest();

if (CHECK_MODE) {
  let drift = 0;
  for (const [target, content] of Object.entries(outputs)) {
    const existing = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
    if (existing !== content) {
      drift += 1;
      console.log(`DRIFT  ${path.relative(ROOT, target)}`);
    }
  }
  if (newJkBmsJs !== currentJkBmsJs) {
    drift += 1;
    console.log(`DRIFT  jk_bms.js (generated block out of date)`);
  }
  // Manifest presence/hash-match check: catches a generation run that was
  // interrupted AFTER writing some output files but BEFORE the manifest
  // (written last, see the write phase below) — a state where individual
  // files might each look superficially valid but do not all belong to the
  // SAME completed generation (spec Крок K.4/K.6).
  if (!fs.existsSync(MANIFEST_PATH)) {
    drift += 1;
    console.log(`DRIFT  protocol/generated/.generation-manifest.json is missing — no completed generation is recorded`);
  } else {
    let onDiskManifest = null;
    try { onDiskManifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8")); } catch (e) { /* treated as drift below */ }
    if (!onDiskManifest || JSON.stringify(onDiskManifest) !== JSON.stringify(manifest)) {
      drift += 1;
      console.log(`DRIFT  protocol/generated/.generation-manifest.json does not match the current canonical source's expected output hashes`);
    }
  }
  if (drift === 0) {
    console.log("generate.js --check: no drift. All generated artifacts match the canonical source.");
    process.exit(0);
  } else {
    console.log(`generate.js --check: ${drift} artifact(s) out of date. Run 'node tools/protocol/generate.js' to regenerate.`);
    process.exit(1);
  }
} else {
  // Journaled publication. Every target (including the manifest) is staged
  // and fsync'd first. Existing targets are then backed up before publication;
  // any ordinary error or injected boundary failure restores the complete old
  // generation. A process lock prevents concurrent publishers. Consumers must
  // treat a generation as valid only when the full manifest matches.
  const lockPath = path.join(ROOT, "protocol", "generated", ".generation.lock");
  fs.mkdirSync(path.dirname(lockPath), { recursive: true });
  let lockFd;
  try {
    lockFd = fs.openSync(lockPath, "wx", 0o600);
    fs.writeFileSync(lockFd, `${process.pid}\n`, "utf8");
    fs.fsyncSync(lockFd);
  } catch (e) {
    console.error(`GENERATOR_LOCKED: another publisher holds ${path.relative(ROOT, lockPath)}`);
    process.exit(2);
  }

  const transactionOutputs = {
    ...outputs,
    [jkBmsJsPath]: newJkBmsJs,
    [MANIFEST_PATH]: JSON.stringify(manifest, null, 2) + "\n",
  };
  const staged = [];
  const backups = [];
  const published = [];
  const failAt = process.env.PROTOCOL_GENERATOR_FAIL_AT || "";
  const inject = (boundary) => {
    if (failAt === boundary) throw new Error(`INJECTED_PUBLISH_FAILURE:${boundary}`);
  };
  const fsyncFile = (p) => {
    const fd = fs.openSync(p, "r");
    try { fs.fsyncSync(fd); } finally { fs.closeSync(fd); }
  };
  const fsyncDir = (p) => {
    const fd = fs.openSync(p, "r");
    try { fs.fsyncSync(fd); } finally { fs.closeSync(fd); }
  };

  try {
    let index = 0;
    for (const [target, content] of Object.entries(transactionOutputs)) {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      const tmp = path.join(path.dirname(target), `.${path.basename(target)}.tmp-${process.pid}-${index}`);
      fs.writeFileSync(tmp, content, "utf8");
      fsyncFile(tmp);
      staged.push([tmp, target]);
      index += 1;
    }
    inject("before:publish");
    for (let i = 0; i < staged.length; i += 1) {
      const [tmp, target] = staged[i];
      inject(`before:${i}`);
      const backup = `${target}.bak-${process.pid}`;
      if (fs.existsSync(target)) {
        fs.renameSync(target, backup);
        backups.push([backup, target]);
      }
      fs.renameSync(tmp, target);
      published.push(target);
      fsyncDir(path.dirname(target));
      inject(`after:${i}`);
    }
    for (const [backup] of backups) fs.unlinkSync(backup);
    for (const target of published) console.log(`wrote ${path.relative(ROOT, target)}`);
    console.log(`generation_id=${manifest.generation_id}`);
  } catch (e) {
    for (const target of published.reverse()) {
      try { if (fs.existsSync(target)) fs.unlinkSync(target); } catch (_) { /* best effort */ }
    }
    for (const [backup, target] of backups.reverse()) {
      try { if (fs.existsSync(backup)) fs.renameSync(backup, target); } catch (_) { /* best effort */ }
    }
    for (const [tmp] of staged) {
      try { if (fs.existsSync(tmp)) fs.unlinkSync(tmp); } catch (_) { /* best effort */ }
    }
    console.error(`GENERATOR_PUBLISH_ROLLBACK: ${e.message}`);
    process.exitCode = 1;
  } finally {
    try { if (lockFd !== undefined) fs.closeSync(lockFd); } catch (_) { /* best effort */ }
    try { fs.unlinkSync(lockPath); } catch (_) { /* best effort */ }
  }
  if (!process.exitCode) {
    console.log(`\ncatalog_version=${catalogVersion} source_hash=${canonicalHash}`);
    console.log(`${registerDoc.registers.length} registers, ${allRegisterFields.length} fields, ${nonRegisterDoc.entities.length} non-register entities.`);
  }
}
