#!/usr/bin/env node
"use strict";

// STRUCTURAL TEST -- source-inspection only, no DOM/jsdom interaction.
// Written 2026-09-21 (user-directed deployment-gate audit, Task 4/5): the
// Stage 4 write registry frontend panel (WRITE_REGISTRY, generated by
// build_stage4_rw_inventory.js; renderWriteRegistry()/submitRegisterWrite()
// hand-written in jk_bms.js) is new this round and does not yet have a
// full interactive DOM harness (this project's own DOM tests each hand-
// roll a bespoke FakeNode shim per file -- a real one for this panel is a
// legitimate, separate, larger follow-on, not attempted here given this
// round's remaining scope). This test proves the STATIC properties that
// ARE checkable without one: the generated catalog block exists and has
// the right shape/counts, the hand-written render/submit functions exist
// and reference the real production endpoints (never a hand-typed
// duplicate of the URL), the HTML panel/i18n scaffolding exists in both
// languages, and WRITE_REGISTRY's counts agree with
// stage4_rw_inventory.json's own authoritative classification. It does
// NOT prove: rows actually render to a live DOM, a click actually fires a
// preflight fetch, a confirm dialog actually appears, or SSE/draft
// survival actually works -- those need the DOM harness this test
// explicitly does not attempt.

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..", "..");
const jsSource = fs.readFileSync(path.join(ROOT, "jk_bms.js"), "utf8");
const htmlSourceIsInline = true; // the panel markup is a template literal inside jk_bms.js, not a separate .html file
const writeRegistry = JSON.parse(fs.readFileSync(path.join(ROOT, "protocol", "generated", "write_registry.json"), "utf8"));
const inventory = JSON.parse(fs.readFileSync(path.join(ROOT, "protocol", "generated", "stage4_rw_inventory.json"), "utf8"));

let checks = 0;
let failures = 0;
function check(name, pass, detail = "") {
  checks += 1;
  if (!pass) failures += 1;
  console.log(`${pass ? "PASS" : "FAIL"}  ${name}${detail ? ` -- ${detail}` : ""}`);
}

// --- generated block presence/shape ---
check("jk_bms.js has the GENERATED WRITE REGISTRY begin marker",
  jsSource.includes("// >>> BEGIN GENERATED WRITE REGISTRY"));
check("jk_bms.js has the GENERATED WRITE REGISTRY end marker",
  jsSource.includes("// <<< END GENERATED WRITE REGISTRY"));

const blockMatch = jsSource.match(/\/\/ >>> BEGIN GENERATED WRITE REGISTRY[\s\S]*?\/\/ <<< END GENERATED WRITE REGISTRY/);
check("the generated block can be isolated from the rest of the file", !!blockMatch);
const block = blockMatch ? blockMatch[0] : "";

const liveKeysInSource = [...block.matchAll(/key:\s*"([a-z0-9_]+)"[^}]*submitPolicy:\s*"live"/g)].map((m) => m[1]);
const authKeysInSource = [...block.matchAll(/key:\s*"([a-z0-9_]+)"[^}]*submitPolicy:\s*"authorization_required"/g)].map((m) => m[1]);
const liveEntries = writeRegistry.entries.filter((e) => e.submit_policy === "live");
const authEntries = writeRegistry.entries.filter((e) => e.submit_policy === "authorization_required");

check("embedded WRITE_REGISTRY.live key set exactly matches write_registry.json's live entries",
  liveKeysInSource.length === liveEntries.length && liveEntries.every((e) => liveKeysInSource.includes(e.key)),
  `embedded=${liveKeysInSource.length} catalog=${liveEntries.length}`);
check("embedded WRITE_REGISTRY.authorizationRequired key set exactly matches write_registry.json's authorization-required entries",
  authKeysInSource.length === authEntries.length && authEntries.every((e) => authKeysInSource.includes(e.key)),
  `embedded=${authKeysInSource.length} catalog=${authEntries.length}`);

const blockedRowsExpected = inventory.rows.filter((r) => r.stage4_state === "blocked" && r.canonical_key);
const blockedKeysInSource = [...block.matchAll(/key:\s*"([a-z0-9_]+)",\s*address:\s*\d+,\s*writeSafetyClass:[^}]*reason:/g)].map((m) => m[1]);
check("embedded WRITE_REGISTRY.blocked key set exactly matches stage4_rw_inventory.json's blocked rows",
  blockedKeysInSource.length === blockedRowsExpected.length && blockedRowsExpected.every((r) => blockedKeysInSource.includes(r.canonical_key)),
  `embedded=${blockedKeysInSource.length} inventory=${blockedRowsExpected.length}`);

check("exactly 5 live + 37 authorization-required + 37 blocked = 79 rows (the plan's own UI matrix)",
  liveEntries.length === 5 && authEntries.length === 37 && blockedRowsExpected.length === 37,
  `live=${liveEntries.length} auth=${authEntries.length} blocked=${blockedRowsExpected.length}`);

// --- hand-written render/submit functions exist and wire the REAL endpoints ---
check("renderWriteRegistry() is defined", /function renderWriteRegistry\s*\(/.test(jsSource));
check("submitRegisterWrite() is defined", /async function submitRegisterWrite\s*\(/.test(jsSource));
check("fetchRegisterWritePreflight() is defined", /async function fetchRegisterWritePreflight\s*\(/.test(jsSource));
check("submitRegisterWrite() calls the real POST /settings/register-write endpoint (not a hand-typed /number/... duplicate)",
  /`\/settings\/register-write\?key=\$\{encodeURIComponent\(entry\.key\)\}&value=\$\{encodeURIComponent\(String\(value\)\)\}&submit_policy=live`/.test(jsSource));
check("fetchRegisterWritePreflight() calls the real GET /settings/register-write/preflight endpoint",
  /\/settings\/register-write\/preflight\?key=/.test(jsSource));
check("submitRegisterWrite() requires an explicit confirmation (window.confirm) before submitting",
  /window\.confirm\(t\("writeRegistry\.confirmPrompt"/.test(jsSource));
check("submitRegisterWrite() rejects submission when preflight did not report ready:true",
  /body\.ready !== true/.test(jsSource));
check("submitRegisterWrite() blocks a resubmit while this key's transaction is already active (single-flight)",
  /activeTransactionKeys\.has\(entry\.key\)/.test(jsSource));
check("live rows pass a real `address` to runRegisterWriteTransaction() (authoritative write_tx_snapshot correlation, not entity-state polling)",
  /address:\s*entry\.address,[\s\S]{0,200}label:\s*`\$\{writeRegistryFieldLabel/.test(jsSource));

// --- async accepted/request_id/status-poll contract (2026-09-21 second
// corrective pass) -- proves the OLD synchronous tx_id-in-the-POST-
// response contract is genuinely gone, not merely unused.
check("postRegisterWrite() is defined (the dedicated async POST, never reusing postCommand())",
  /async function postRegisterWrite\s*\(/.test(jsSource));
check("fetchRegisterWriteStatus() is defined (the GET .../status poll primitive)",
  /async function fetchRegisterWriteStatus\s*\(/.test(jsSource));
check("pollRegisterWriteStatus() is defined and bounded (a real timeout budget constant, not an unbounded loop)",
  /function pollRegisterWriteStatus\s*\(/.test(jsSource) && /REGISTER_WRITE_POLL_TIMEOUT_MS/.test(jsSource));
check("runRegisterWriteTransaction() is defined (the dedicated async register-write state machine)",
  /function runRegisterWriteTransaction\s*\(/.test(jsSource));
check("submitRegisterWrite() calls runRegisterWriteTransaction(), not the generic writeTransaction()",
  (() => {
    const fnMatch = jsSource.match(/async function submitRegisterWrite\s*\([^)]*\)\s*\{[\s\S]*?\n  \}/);
    if (!fnMatch) return false;
    const body = fnMatch[0];
    return body.includes("runRegisterWriteTransaction({") && !/[^.]\bwriteTransaction\(\{/.test(body);
  })());
check("postRegisterWrite() sends an empty POST body (every parameter travels in the query string)",
  /body:\s*""/.test(jsSource));
check("runRegisterWriteTransaction() parses status:\"accepted\" and a real request_id from the POST response, never a tx_id",
  /body\.status !== "accepted" \|\| !\(Number\(body\.request_id\) > 0\)/.test(jsSource));
check("runRegisterWriteTransaction() polls GET /settings/register-write/status with the real request_id",
  /\/settings\/register-write\/status\?request_id=/.test(jsSource));
check("runRegisterWriteTransaction() correlates the write_tx_snapshot by the EXACT accepted tx_id, never \"tx_id > startTxId\"",
  /entry\.tx_id !== acceptedTxId/.test(jsSource) && !/tx_id\s*>\s*acceptedTxId/.test(jsSource));
check("runRegisterWriteTransaction() surfaces a rejected status poll immediately with the real backend reason",
  /statusBody\.status === "rejected"[\s\S]{0,600}writeRegistry\.rejected/.test(jsSource));
check("runRegisterWriteTransaction() treats \"expired\" as a distinct terminal outcome",
  /statusBody\.status === "expired"/.test(jsSource));
check("runRegisterWriteTransaction() treats an unrecognized/\"unknown\" status as fail-closed, never a fabricated tx_id",
  /statusBody\.status !== "accepted" \|\| !\(Number\(statusBody\.tx_id\) > 0\)/.test(jsSource));
check("a poll that never resolves within the bounded timeout is a distinct TIMEOUT outcome (never hangs forever)",
  /statusBody\.status === "timeout"/.test(jsSource));
check("setup_passcode/unverifiable fields are only ever shown as sent AFTER the status poll's own real acceptance, never on the POST's bare accepted response",
  /if \(cfg\.unverifiable\) \{[\s\S]{0,600}finish\(TX_STATE\.SENT_UNVERIFIED/.test(jsSource));

// --- authorization-required/blocked rows never render an active editor ---
check("authorization-required rows render a disabled input (never an active editor)",
  /group === "authorizationRequired"[\s\S]{0,400}input\.disabled = true/.test(jsSource));
check("blocked rows render no input element at all (else branch has no `new_string`-style input creation)",
  (() => {
    const elseBranch = jsSource.match(/\} else \{\s*const note = document\.createElement\("span"\);\s*note\.className = "write-registry-note";\s*note\.textContent = t\("writeRegistry\.blockedNote"/);
    return !!elseBranch;
  })());

// --- HTML panel + i18n scaffolding, both languages ---
// Finish-the-Settings-architecture batch (2026-09-22): the standalone
// write-registry panel's own HTML container/message element and its
// boot-time render call are retired -- the generic Settings catalog
// (#settingsCatalogList, renderSettingsCatalog()) is the ONE active
// Settings DOM surface now (see test_settings_catalog.js). This proves
// removal, not presence: no duplicate active DOM surface.
check("panel markup no longer declares the retired writeRegistryList container", !jsSource.includes('id="writeRegistryList"'));
check("panel markup no longer declares the retired writeRegistryMessage status element", !jsSource.includes('id="writeRegistryMessage"'));
check("build() no longer calls renderWriteRegistry() during boot", !/renderWriteRegistry\(\);/.test(jsSource));
check("panel markup declares the replacement settingsCatalogList container", jsSource.includes('id="settingsCatalogList"'));
check("build() calls renderSettingsCatalog() during boot", /renderCellCompositeList\(\);\s*\n\s*renderSettingsCatalog\(\);/.test(jsSource));

for (const lang of ["en", "uk"]) {
  const langBlockMatch = jsSource.match(new RegExp(`${lang}:\\s*\\{[\\s\\S]*?writeRegistry:\\s*\\{([\\s\\S]*?)\\n\\s*\\},\\n\\s*diagnostics:`));
  check(`writeRegistry i18n block exists for lang="${lang}"`, !!langBlockMatch);
  if (langBlockMatch) {
    for (const requiredKey of ["title", "caption", "live", "authorizationRequired", "blocked", "write", "confirmPrompt", "preflightFailed", "notReady", "authorizationRequiredNote", "blockedNote"]) {
      check(`writeRegistry.${requiredKey} is defined for lang="${lang}"`, new RegExp(`\\b${requiredKey}:`).test(langBlockMatch[1]));
    }
  }
}

// --- test-hook exposure for a future real DOM harness ---
check("renderWriteRegistry/submitRegisterWrite/WRITE_REGISTRY are exposed via __JK_BMS_TEST_HOOKS__",
  /renderWriteRegistry, submitRegisterWrite, WRITE_REGISTRY,/.test(jsSource));

console.log(`\nwrite registry UI structural summary: ${checks - failures}/${checks} passed`);
process.exit(failures ? 1 : 0);
