#!/usr/bin/env node
"use strict";

// STRUCTURAL TEST -- source-inspection only, no DOM/jsdom interaction.
// Mirrors test_write_registry_ui_structural.js's own role for Stage 4:
// proves the STATIC properties of the Stage 5 service-action panel
// (SERVICE_ACTIONS, generated by build_stage5_service_actions.js;
// renderServiceActionRow()/renderServiceActions()/relocalizeServiceActions()
// hand-written in jk_bms.js) that are checkable without a live DOM harness.
// Does NOT prove rows actually paint pixels in a real browser -- that was
// separately verified once, interactively, against the mock server this
// round; this test guards against future source-level regressions.

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..", "..");
const jsSource = fs.readFileSync(path.join(ROOT, "jk_bms.js"), "utf8");
const inventory = JSON.parse(fs.readFileSync(path.join(ROOT, "protocol", "generated", "stage5_service_action_inventory.json"), "utf8"));

let checks = 0;
let failures = 0;
function check(name, pass, detail = "") {
  checks += 1;
  if (!pass) failures += 1;
  console.log(`${pass ? "PASS" : "FAIL"}  ${name}${detail ? ` -- ${detail}` : ""}`);
}

// --- generated block presence/shape ---
check("jk_bms.js has the GENERATED SERVICE ACTIONS begin marker",
  jsSource.includes("// >>> BEGIN GENERATED SERVICE ACTIONS"));
check("jk_bms.js has the GENERATED SERVICE ACTIONS end marker",
  jsSource.includes("// <<< END GENERATED SERVICE ACTIONS"));

const blockMatch = jsSource.match(/const SERVICE_ACTIONS = Object\.freeze\(\[[\s\S]*?\]\);/);
check("the SERVICE_ACTIONS literal can be isolated from the rest of the file", !!blockMatch);
const block = blockMatch ? blockMatch[0] : "";

const keysInSource = [...block.matchAll(/key:\s*"([a-z0-9_]+)"/g)].map((m) => m[1]);
check("SERVICE_ACTIONS key set exactly matches the inventory's 8 keys, in order",
  keysInSource.length === inventory.rows.length &&
  keysInSource.every((k, i) => k === inventory.rows[i].key),
  `embedded=${JSON.stringify(keysInSource)} inventory=${JSON.stringify(inventory.rows.map((r) => r.key))}`);

const blockedKeysInSource = [...block.matchAll(/key:\s*"([a-z0-9_]+)"[^}]*state:\s*"blocked"/g)].map((m) => m[1]);
const blockedRowsExpected = inventory.rows.filter((r) => r.implementation_state === "blocked");
check("SERVICE_ACTIONS blocked-state entries exactly match the inventory's blocked rows (currently all 8)",
  blockedKeysInSource.length === blockedRowsExpected.length &&
  blockedRowsExpected.every((r) => blockedKeysInSource.includes(r.key)),
  `embedded_blocked=${blockedKeysInSource.length} inventory_blocked=${blockedRowsExpected.length}`);

check("exactly 8 rows total, 0 software-ready (this round's honest evidence-driven outcome)",
  keysInSource.length === 8 && blockedKeysInSource.length === 8);

// --- hand-written render/relocalize functions exist ---
check("serviceActionLabel() is defined", /function serviceActionLabel\s*\(/.test(jsSource));
check("renderServiceActionRow() is defined", /function renderServiceActionRow\s*\(/.test(jsSource));
check("renderServiceActions() is defined", /function renderServiceActions\s*\(/.test(jsSource));
check("relocalizeServiceActions() is defined", /function relocalizeServiceActions\s*\(/.test(jsSource));

// --- no row ever contains an input or a button (no dispatch endpoint exists
// yet for ANY command -- neither software-ready nor blocked rows may render
// an executable control) ---
check("renderServiceActionRow() never creates an <input> or <button> element",
  (() => {
    const fnMatch = jsSource.match(/function renderServiceActionRow\s*\([^)]*\)\s*\{[\s\S]*?\n  \}/);
    if (!fnMatch) return false;
    const body = fnMatch[0];
    return !/createElement\("input"\)/.test(body) && !/createElement\("button"\)/.test(body);
  })());
check("renderServiceActions() attaches no click handler (nothing to submit)",
  (() => {
    const fnMatch = jsSource.match(/function renderServiceActions\s*\([^)]*\)\s*\{[\s\S]*?\n  \}/);
    if (!fnMatch) return false;
    return !/addEventListener\("click"/.test(fnMatch[0]);
  })());

// --- both states branch on the real SERVICE_ACTIONS `state` field ---
check("renderServiceActionRow() branches on entry.state === \"service-action-software-ready\" (never hardcodes blocked)",
  /entry\.state === "service-action-software-ready"/.test(jsSource));
check("blocked branch renders serviceActions.blockedNote with the real blockedReason",
  /t\("serviceActions\.blockedNote",\s*\{\s*reason:\s*entry\.blockedReason/.test(jsSource));
check("software-ready branch renders serviceActions.softwareReadyNoDispatchNote (distinct from blockedNote)",
  /t\("serviceActions\.softwareReadyNoDispatchNote"\)/.test(jsSource));

// --- HTML panel scaffolding ---
// Finish-the-Settings-architecture batch (2026-09-22): the standalone
// service-actions panel is retired -- the generic Settings catalog
// (#settingsCatalogList, renderSettingsCatalog()) renders all 8 W
// commands as generic rows now (access==="W" branch), reading the SAME
// SERVICE_ACTIONS-equivalent data straight from SETTINGS_VIEW_MODEL (see
// test_settings_catalog.js). This proves removal, not presence.
check("panel markup no longer declares the retired serviceActionsList container", !jsSource.includes('id="serviceActionsList"'));
check("build() no longer calls renderServiceActions() during boot", !/renderServiceActions\(\);/.test(jsSource));
check("refreshAllDynamicText() no longer calls relocalizeServiceActions() on language switch", !/relocalizeServiceActions\(\);/.test(jsSource));
check("build() calls renderSettingsCatalog() during boot instead", /renderSettingsCatalog\(\);/.test(jsSource));
check("refreshAllDynamicText() calls relocalizeSettingsCatalog() on language switch instead", /relocalizeSettingsCatalog\(\);/.test(jsSource));

// --- i18n scaffolding, both languages ---
for (const lang of ["en", "uk"]) {
  const langBlockMatch = jsSource.match(new RegExp(`${lang}:\\s*\\{[\\s\\S]*?serviceActions:\\s*\\{([\\s\\S]*?)\\n\\s*\\},\\n\\s*diagnostics:`));
  check(`serviceActions i18n block exists for lang="${lang}"`, !!langBlockMatch);
  if (langBlockMatch) {
    for (const requiredKey of ["title", "caption", "blockedNote", "softwareReadyNoDispatchNote", "commands"]) {
      check(`serviceActions.${requiredKey} is defined for lang="${lang}"`, new RegExp(`\\b${requiredKey}:`).test(langBlockMatch[1]));
    }
    for (const cmdKey of inventory.rows.map((r) => r.key)) {
      check(`serviceActions.commands.${cmdKey} is defined for lang="${lang}"`, new RegExp(`\\b${cmdKey}:`).test(langBlockMatch[1]));
    }
  }
}

// --- test-hook exposure for a future real DOM harness ---
check("renderServiceActions/relocalizeServiceActions/SERVICE_ACTIONS are exposed via __JK_BMS_TEST_HOOKS__",
  /renderServiceActions, relocalizeServiceActions, SERVICE_ACTIONS,/.test(jsSource));

console.log(`\nStage 5 service-action UI structural summary: ${checks - failures}/${checks} passed`);
process.exit(failures ? 1 : 0);
