#!/usr/bin/env python3
"""Build a deterministic claim-aware index of the pinned upstream YAML."""
import argparse
import hashlib
import json
import os
import re
import sys

SRC_PATH = "protocol/evidence/upstream_esp32-jk-pb-modbus-example.yaml"
DEFAULT_OUT = "protocol/evidence/upstream_index.json"
COMMIT_SHA = "08f25eb4941b03b6ee0b6c38660aeadfc4ef7cd1"
COMMENT_RE = re.compile(r"^\s*#\s*(0x[0-9A-Fa-f]{4})\s+(\d+)\s+(\S+)\s+(\d+)\s+(R|RW)\s+(\S+)(?:\s+(\S+))?\s*$")
LOOSE_COMMENT_RE = re.compile(r"^\s*#\s*(0x[0-9A-Fa-f]{4})\b(.*)$")
ADDRESS_RE = re.compile(r"^(\s*)address:\s*(0x[0-9A-Fa-f]{4})\b")
PLATFORM_RE = re.compile(r"^(\s*)-\s+platform:\s*(\S+)")
KEY_RE = re.compile(r"^\s+(id|name|register_type|value_type|register_count|response_size|unit_of_measurement|internal):\s*(.*?)\s*$")


def norm(token):
    return f"0x{token[2:].upper()}"


def entity_block(lines, address_line):
    address_indent = len(ADDRESS_RE.match(lines[address_line]).group(1))
    start = indent = None
    platform = None
    for index in range(address_line - 1, -1, -1):
        match = PLATFORM_RE.match(lines[index])
        if match and len(match.group(1)) < address_indent:
            start, indent, platform = index, len(match.group(1)), match.group(2)
            break
        if lines[index] and not lines[index][0].isspace():
            break
    if start is None:
        return None
    end = len(lines)
    for index in range(start + 1, len(lines)):
        match = PLATFORM_RE.match(lines[index])
        if match and len(match.group(1)) == indent:
            end = index
            break
        if lines[index] and not lines[index][0].isspace():
            end = index
            break
    block_lines = lines[start:end]
    block = {"kind": "yaml_entity_block", "platform": platform}
    for line in block_lines:
        match = KEY_RE.match(line)
        if match and match.group(1) not in block:
            block[match.group(1)] = match.group(2).strip('"\'')
    block.update({
        "start_line": start + 1,
        "end_line": end,
        "address_line": address_line + 1,
        "has_filters": any(re.match(r"^\s+filters:\s*$", line) for line in block_lines),
        "has_lambda": any("lambda:" in line for line in block_lines),
        "has_set_action": any(re.match(r"^\s+set_action:\s*$", line) for line in block_lines),
    })
    return block


def build():
    raw = open(SRC_PATH, "rb").read()
    lines = raw.decode("utf-8").splitlines()
    address_index = {}
    for line_number, line in enumerate(lines, 1):
        match = COMMENT_RE.match(line)
        if match:
            address = norm(match.group(1))
            address_index.setdefault(address, []).append({
                "kind": "comment_table_row",
                "start_line": line_number,
                "end_line": line_number,
                "address": address,
                "byte_offset": int(match.group(2)),
                "wire_type": match.group(3),
                "payload_bytes": int(match.group(4)),
                "declared_access": match.group(5).lower(),
                "symbol": match.group(6),
                "displayed_unit": match.group(7) or "",
            })
        else:
            loose = LOOSE_COMMENT_RE.match(line)
            if loose:
                address = norm(loose.group(1))
                address_index.setdefault(address, []).append({
                    "kind": "comment_raw_unparsed",
                    "start_line": line_number,
                    "end_line": line_number,
                    "address": address,
                    "raw_columns": loose.group(2).strip(),
                })
    for index, line in enumerate(lines):
        match = ADDRESS_RE.match(line)
        if not match:
            continue
        block = entity_block(lines, index)
        if block:
            address_index.setdefault(norm(match.group(2)), []).append(block)
    return {
        "$comment": "GENERATED by build_upstream_index.py from an immutable commit snapshot; comment rows and YAML entity blocks are distinct evidence capabilities.",
        "source_path": SRC_PATH,
        "source_sha256": hashlib.sha256(raw).hexdigest(),
        "upstream_commit_sha": COMMIT_SHA,
        "total_lines": len(lines),
        "unique_addresses_referenced": len(address_index),
        "address_index": dict(sorted(address_index.items())),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = build()
    text = json.dumps(output, indent=2, ensure_ascii=False) + "\n"
    if args.check:
        # release_generation_id is pipeline.js-owned metadata, stamped onto
        # the committed artifact by a post-processing step this script never
        # runs itself -- strip it before comparing so this standalone check
        # verifies only the payload this script owns (see the identical note
        # in build_workbook_v2_index.py's --check block).
        existing = open(args.output, encoding="utf-8").read() if os.path.exists(args.output) else None
        existing_payload = None
        if existing is not None:
            try:
                parsed = json.loads(existing)
                parsed.pop("release_generation_id", None)
                existing_payload = json.dumps(parsed, indent=2, ensure_ascii=False) + "\n"
            except (json.JSONDecodeError, AttributeError):
                existing_payload = None
        if existing_payload != text:
            print("UPSTREAM_INDEX_STALE", file=sys.stderr)
            return 1
        print(f"upstream-index PASS addresses={output['unique_addresses_referenced']}")
        return 0
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"wrote {args.output}; addresses={output['unique_addresses_referenced']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
