#!/usr/bin/env python3
"""Deterministic, re-runnable evidence indexer for the verified V2 workbook.

Reads `LiFePO4_BMS_Parameters_registers-V2_verified.xlsx`'s "Реєстр
параметрів" sheet and writes protocol/evidence/workbook_v2_index.json: a
base_address -> row(s) normalized index — the V2 counterpart to
workbook_index.json, which stays scoped to the deprecated V1 workbook (see
its own "$deprecated" note; it is retained only for historical/regression
comparison, not superseded in place, since existing evidence[] citations in
registers.canonical.json still reference it).

This is what protocol/evidence/build_claim_matrix.js and
tools/protocol/lib/semantic-checks.js's index-backed-evidence check consult
for any registers.canonical.json evidence citation of the
workbook_lifepo4_bms_parameters_registers_v2 source_id (protocol/evidence/
sources.json). A non-empty locator string alone is never accepted as proof —
same rule as the V1 path (spec Крок C).

Unlike the V1 workbook, the V2 workbook is itself a repo-committed evidence
file (protocol/evidence/LiFePO4_BMS_Parameters_registers-V2_verified.xlsx),
not a personal Downloads path — defaulting --workbook to its repo-relative
location here is the same category of hardcoding build_workbook_index.py
itself already does for OUT_PATH/SOURCES_PATH, not the personal-filesystem-
path defect CODEX P1-8 fixed for the V1 script.

Reuses the same stdlib-only OOXML sheet parser (build_workbook_index.py) and
the same address-string parser (build_v2_manifest.py's parse_address) that
protocol/generated/bms_v1_1_manifest.json is built with — including that
parser's existing limitation of reading only the first "0xNNNN" token in an
address cell. Any V2 row whose address cell packs more than one address
token is therefore indexed under its first token only, exactly as the V2
manifest already resolves it; this script does not invent a different,
divergent reading of the same ambiguous cells.

Run:
  python3 protocol/evidence/build_workbook_v2_index.py
  python3 protocol/evidence/build_workbook_v2_index.py --workbook /path/to/file.xlsx
  python3 protocol/evidence/build_workbook_v2_index.py --check
"""
import argparse
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from build_workbook_index import parse_xlsx_sheet  # noqa: E402
from build_v2_manifest import get_field, parse_address  # noqa: E402

REGISTRY_SHEET = "Реєстр параметрів"
OUT_PATH = "protocol/evidence/workbook_v2_index.json"
SOURCES_PATH = "protocol/evidence/sources.json"
SOURCE_ID = "workbook_lifepo4_bms_parameters_registers_v2"


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def build_index(workbook_path):
    file_sha256 = sha256_file(workbook_path)
    rows, dimensions = parse_xlsx_sheet(workbook_path, REGISTRY_SHEET)
    total_rows = max((int(k) for k in rows), default=0)

    address_index = {}
    rows_with_address = 0
    parse_errors = []
    for row_number in sorted(rows.keys(), key=int):
        if int(row_number) == 1:
            continue  # header
        row = rows[row_number]
        address_raw = get_field(row, "address")
        if not address_raw:
            continue
        rows_with_address += 1
        address_info = parse_address(address_raw)
        base = address_info.get("base_address")
        if not base or address_info.get("parse_error"):
            parse_errors.append({"row": int(row_number), "address_cell_raw": address_raw})
            continue
        entry = {
            "row": int(row_number),
            "sheet": REGISTRY_SHEET,
            "cell_range": f"A{row_number}:O{row_number}",
            "address_cell_raw": address_raw,
            "name_ua": get_field(row, "name_ua"),
            "name_prog": get_field(row, "name_prog"),
            "access": get_field(row, "access"),
            "byte_qualifier": address_info.get("byte_half"),
            "bit": address_info.get("bit"),
            "bit_unspecified": address_info.get("bit_unspecified"),
        }
        address_index.setdefault(base, []).append(entry)

    output = {
        "$comment": "GENERATED by protocol/evidence/build_workbook_v2_index.py — do not hand-edit. "
                     "V2 counterpart to workbook_index.json (which remains scoped to the deprecated "
                     "V1 workbook). Consulted by protocol/evidence/build_claim_matrix.js and "
                     "tools/protocol/lib/semantic-checks.js for any registers.canonical.json evidence "
                     f"citation of source_id \"{SOURCE_ID}\".",
        "source_basename": os.path.basename(workbook_path),
        "source_sha256": file_sha256,
        "sheet_name": REGISTRY_SHEET,
        "sheet_dimensions": dimensions,
        "total_rows": total_rows,
        "rows_with_address_cell": rows_with_address,
        "unique_addresses": len(address_index),
        "address_parse_errors": parse_errors,
        "address_index": dict(sorted(address_index.items())),
    }
    return output, file_sha256


def resolve_workbook_path(args):
    repo_root = os.path.join(os.path.dirname(__file__), "..", "..")
    default_path = os.path.join(repo_root, "protocol", "evidence",
                                 "LiFePO4_BMS_Parameters_registers-V2_verified.xlsx")
    path = args.workbook or os.environ.get("JK_BMS_WORKBOOK_V2_PATH") or default_path
    if not os.path.isfile(path):
        print(f"ERROR: V2 workbook not found at {path!r}. Pass --workbook, set "
              f"JK_BMS_WORKBOOK_V2_PATH, or restore the repo-committed copy at "
              f"{default_path!r}.", file=sys.stderr)
        sys.exit(2)
    return path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--workbook", help="Path to LiFePO4_BMS_Parameters_registers-V2_verified.xlsx")
    parser.add_argument("--output", default=OUT_PATH)
    parser.add_argument("--check", action="store_true",
                         help="Verify protocol/evidence/workbook_v2_index.json is byte-identical to a fresh build; exit 1 if not.")
    args = parser.parse_args()

    workbook_path = resolve_workbook_path(args)
    output, file_sha256 = build_index(workbook_path)

    manifest = json.load(open(SOURCES_PATH, encoding="utf-8"))
    source = next(s for s in manifest["sources"] if s["source_id"] == SOURCE_ID)
    # Unlike the deprecated V1 workbook's sources.json entry (key "file_sha256"),
    # the V2 workbook entry follows the local_copy_path/local_copy_sha256
    # convention shared with the official PDF source — the two entries predate
    # and postdate that convention respectively, so the key genuinely differs.
    expected_sha256 = source["local_copy_sha256"]
    if file_sha256 != expected_sha256:
        print(f"ERROR: V2 workbook sha256 {file_sha256} does not match the hash recorded in "
              f"protocol/evidence/sources.json ({expected_sha256}) — this is not the same file "
              f"the canonical evidence was reconciled against. Refusing to write a stale/wrong index.",
              file=sys.stderr)
        sys.exit(1)

    new_text = json.dumps(output, indent=2, ensure_ascii=False, default=str) + "\n"

    if args.check:
        old_text = open(args.output, encoding="utf-8").read() if os.path.exists(args.output) else None
        if old_text != new_text:
            print(f"WORKBOOK_V2_INDEX_STALE: {args.output}", file=sys.stderr)
            sys.exit(1)
        print(f"workbook-v2-index PASS rows={output['total_rows']} addresses={output['unique_addresses']}")
        return

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(new_text)

    print(f"source_sha256={file_sha256}")
    print(f"rows={output['total_rows']} rows_with_address_cell={output['rows_with_address_cell']} "
          f"unique_addresses={output['unique_addresses']} parse_errors={len(output['address_parse_errors'])}")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
