#!/usr/bin/env python3
"""Build a deterministic, entity-associated index of the project YAML."""
import argparse
import hashlib
import json
import os
import re
import sys

SRC_PATH = "batterylifepo4.yaml"
DEFAULT_OUT = "protocol/evidence/implementation_index.json"
ADDRESS_RE = re.compile(r"^(\s*)address:\s*(0x[0-9A-Fa-f]{4})\b")
PLATFORM_RE = re.compile(r"^(\s*)-\s+platform:\s*(\S+)")
KEY_RE = re.compile(r"^\s+(id|name|register_type|value_type|register_count|response_size|unit_of_measurement|internal):\s*(.*?)\s*$")


def entity_block(lines, address_line):
    start = None
    indent = None
    platform = None
    for i in range(address_line - 1, -1, -1):
        match = PLATFORM_RE.match(lines[i])
        if match and len(match.group(1)) < len(ADDRESS_RE.match(lines[address_line]).group(1)):
            start, indent, platform = i, len(match.group(1)), match.group(2)
            break
        if lines[i] and not lines[i][0].isspace():
            break
    if start is None:
        return None
    end = len(lines)
    for i in range(start + 1, len(lines)):
        match = PLATFORM_RE.match(lines[i])
        if match and len(match.group(1)) == indent:
            end = i
            break
        if lines[i] and not lines[i][0].isspace():
            end = i
            break
    block = lines[start:end]
    fields = {"platform": platform}
    for line in block:
        match = KEY_RE.match(line)
        if match and match.group(1) not in fields:
            fields[match.group(1)] = match.group(2).strip('"\'')
    fields.update({
        "start_line": start + 1,
        "end_line": end,
        "address_line": address_line + 1,
        "has_filters": any(re.match(r"^\s+filters:\s*$", line) for line in block),
        "has_lambda": any("lambda:" in line for line in block),
        "has_set_action": any(re.match(r"^\s+set_action:\s*$", line) for line in block),
    })
    return fields


def build(source=SRC_PATH):
    raw = open(source, "rb").read()
    lines = raw.decode("utf-8").splitlines()
    address_index = {}
    for index, line in enumerate(lines):
        match = ADDRESS_RE.match(line)
        if not match:
            continue
        address = f"0x{match.group(2)[2:].upper()}"
        block = entity_block(lines, index)
        if block is None:
            continue
        address_index.setdefault(address, []).append(block)
    return {
        "$comment": "GENERATED by build_implementation_index.py; each address is associated with its exact YAML entity block.",
        "source_path": SRC_PATH,
        "source_sha256": hashlib.sha256(raw).hexdigest(),
        "total_lines": len(lines),
        "unique_addresses": len(address_index),
        "address_index": dict(sorted(address_index.items())),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = build()
    text = json.dumps(output, indent=2, ensure_ascii=False) + "\n"
    if args.check:
        # release_generation_id is pipeline.js-owned metadata, stamped onto
        # the committed artifact by a post-processing step this script never
        # runs itself -- strip it before comparing so this standalone check
        # verifies only the payload this script owns (see the identical note
        # in build_workbook_v2_index.py's --check block).
        existing = open(args.output, encoding="utf-8").read() if os.path.exists(args.output) else None
        existing_payload = None
        if existing is not None:
            try:
                parsed = json.loads(existing)
                parsed.pop("release_generation_id", None)
                existing_payload = json.dumps(parsed, indent=2, ensure_ascii=False) + "\n"
            except (json.JSONDecodeError, AttributeError):
                existing_payload = None
        if existing_payload != text:
            print("IMPLEMENTATION_INDEX_STALE", file=sys.stderr)
            return 1
        print(f"implementation-index PASS addresses={output['unique_addresses']}")
        return 0
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"wrote {args.output}; addresses={output['unique_addresses']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
